# Generated by Django 4.2.8 on 2026-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sadness', models.BooleanField(default=False)),
                ('loss_interest', models.BooleanField(default=False)),
                ('sleep_issues', models.BooleanField(default=False)),
                ('appetite_changes', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('worthlessness', models.BooleanField(default=False)),
                ('concentration', models.BooleanField(default=False)),
                ('anxiety', models.BooleanField(default=False)),
                ('panic_attacks', models.BooleanField(default=False)),
                ('physical_symptoms', models.BooleanField(default=False)),
                ('avoidance', models.BooleanField(default=False)),
                ('hopelessness', models.BooleanField(default=False)),
                ('self_harm', models.BooleanField(default=False)),
                ('self_harm_plan', models.BooleanField(blank=True, default=False, null=True)),
                ('substance_use', models.BooleanField(default=False)),
                ('social_withdrawal', models.BooleanField(default=False)),
                ('irritability', models.BooleanField(default=False)),
                ('restlessness', models.BooleanField(default=False)),
                ('paranoia', models.BooleanField(default=False)),
                ('hallucinations', models.BooleanField(default=False)),
                ('mood_swings', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, choices=[('NoConcerns', 'No Significant Concerns'), ('Mild', 'Mild Concerns'), ('Moderate', 'Moderate Concerns'), ('Severe', 'Severe Concerns'), ('Crisis', 'Immediate Crisis')], max_length=20, null=True)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('prediction_method', models.CharField(default='rules', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
